version: '3.8'

services:
  # PocketBase Database
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: bside-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL:-admin@bside.love}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bside-network

  # Ktor Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bside-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - SERVER_PORT=8080
      - ENVIRONMENT=production
    depends_on:
      pocketbase:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bside-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: bside-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - server
      - pocketbase
    networks:
      - bside-network

networks:
  bside-network:
    driver: bridge

volumes:
  pocketbase-data:
