#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.native.cacheKind=none
kotlin.mpp.applyDefaultHierarchyTemplate=false
#Gradle
org.gradle.jvmargs=-Xmx12288M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.vendor=adoptium
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true