#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M
#Gradle
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.vendor=adoptium
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Version
version=0.1.0
org.gradle.java.home=/Users/brentzey/.sdkman/candidates/java/21.0.2-tem
