#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                       ║"
echo "║          🎬 INTERACTIVE GRAFANA DASHBOARD IMPORT 🎬                  ║"
echo "║                                                                       ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will walk you through importing dashboards step-by-step."
echo ""

# Check if Grafana is running
echo "📊 Checking if Grafana is running..."
if curl -s http://localhost:3000/api/health > /dev/null 2>&1; then
    echo "✅ Grafana is running!"
else
    echo "❌ Grafana is not running. Starting stack..."
    docker-compose -f docker-compose.enhanced-lite.yml up -d grafana
    echo "⏳ Waiting 20 seconds for Grafana to start..."
    sleep 20
fi

echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""

# Open Grafana
echo "🌐 Opening Grafana in your browser..."
open http://localhost:3000
sleep 3

echo ""
echo "✅ Grafana should now be open at: http://localhost:3000"
echo ""
echo "🔐 LOGIN CREDENTIALS:"
echo "   Username: admin"
echo "   Password: admin"
echo ""
read -p "Press ENTER after you've logged in..."

echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "📥 DASHBOARD #1: Node Exporter Full (System Metrics)"
echo ""
echo "This dashboard shows CPU, Memory, Disk, and Network metrics."
echo ""
echo "Follow these steps:"
echo "  1. In Grafana's LEFT SIDEBAR, find the '+' icon"
echo "  2. Click it and select 'Import dashboard'"
echo "  3. In the box that appears, type: 1860"
echo "  4. Press Enter or click 'Load'"
echo "  5. Under 'Prometheus' dropdown, select 'Prometheus'"
echo "  6. Click the blue 'Import' button"
echo ""
read -p "Press ENTER after you've imported dashboard 1860..."

echo ""
echo "✅ Great! You should now see live system metrics!"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "📥 DASHBOARD #2: Redis Dashboard (Cache Metrics)"
echo ""
echo "Follow these steps:"
echo "  1. Click the '+' icon again"
echo "  2. Select 'Import dashboard'"
echo "  3. Type: 763"
echo "  4. Click 'Load'"
echo "  5. Select 'Prometheus' datasource"
echo "  6. Click 'Import'"
echo ""
read -p "Press ENTER after you've imported dashboard 763..."

echo ""
echo "✅ Redis metrics are now visible!"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "📥 DASHBOARD #3: Docker Containers (Container Metrics)"
echo ""
echo "Follow these steps:"
echo "  1. Click '+' → 'Import dashboard'"
echo "  2. Type: 14282"
echo "  3. Click 'Load'"
echo "  4. Select 'Prometheus'"
echo "  5. Click 'Import'"
echo ""
read -p "Press ENTER after you've imported dashboard 14282..."

echo ""
echo "✅ All dashboards imported!"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "🚀 GENERATING TRAFFIC TO SEE METRICS UPDATE"
echo ""
echo "I'll now generate some traffic to your backend so you can see"
echo "the metrics change in real-time in your dashboards."
echo ""
read -p "Press ENTER to start generating traffic (or Ctrl+C to skip)..."

echo ""
echo "📊 Generating 100 requests to backend..."
echo ""

for i in {1..100}; do
  curl -s http://localhost:8081/health > /dev/null
  echo -ne "Request $i/100\r"
  sleep 0.1
done

echo ""
echo ""
echo "✅ Traffic generated! Check your Grafana dashboards now!"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "🎉 CONGRATULATIONS! YOU'VE COMPLETED THE SETUP!"
echo ""
echo "What you have now:"
echo "  ✅ 3 professional dashboards imported"
echo "  ✅ Live metrics collecting (815 metrics)"
echo "  ✅ Traffic generated to see data flow"
echo "  ✅ Full observability stack running"
echo ""
echo "🔍 EXPLORE YOUR DASHBOARDS:"
echo ""
echo "1. In Grafana, click 'Home' (top left) → 'Browse'"
echo "2. You'll see all 3 dashboards listed"
echo "3. Click each one to explore"
echo "4. Try changing time range (top right)"
echo "5. Generate more traffic and watch it update!"
echo ""
echo "🎯 NEXT STEPS:"
echo ""
echo "1. Open Prometheus: open http://localhost:9090"
echo "2. Try query: node_memory_MemAvailable_bytes / 1024 / 1024 / 1024"
echo "3. Check logs in Loki (Grafana → Explore → Loki)"
echo "4. View Redis: open http://localhost:8083"
echo "5. View PocketBase: open http://localhost:8092/_/"
echo ""
echo "📚 DOCUMENTATION:"
echo "   ~/bside/LOCAL_WALKTHROUGH.md - Complete guide"
echo "   ~/bside/.code-hq/QUICK_REFERENCE.md - Quick commands"
echo "   ~/bside/.code-hq/OPTION_B_WALKTHROUGH.md - Custom dashboards"
echo ""
echo "🆘 NEED HELP?"
echo "   Run: cat ~/bside/LOCAL_WALKTHROUGH.md | less"
echo ""
echo "────────────────────────────────────────────────────────────────────────"
echo ""
echo "Have fun exploring! 🚀"
echo ""

